title: "Spacy entity categorization"
description: "Entity cat"

vars:
  config: "config"
  gpu: 0
  lang: "en"
  package_name: "spacy_textcat"
  package_version: "0.0.0"
  model: "best"

directories: ["assets", "models", "configs", "metrics", "corpus", "packages", "scripts"]

assets:
  - dest: "assets"
    git:
      repo: "https://github.com/NKayser/bachelor-causal-carbon"
      branch: "main"
      path: "MyCode/data"

workflows:
  all:
    - corpus
    - train

commands:

  - name: corpus
    help: "Convert the data to spaCy's format"
    script:
      - "python scripts/make_corpus.py"
    deps:
      - "scripts/make_corpus.py"
      - "assets/labels_and_predictions.jsonl"
    outputs:
      - "corpus/train.spacy"
      - "corpus/dev.spacy"
      - "corpus/test.spacy"

  - name: config
    help: "update config file from base_config"
    script:
      - "python -m spacy init fill-config configs/base_config.cfg configs/config.cfg \
        --code scripts/custom_span_suggester.py"
    deps:
      - "configs/base_config.cfg"
      - "scripts/custom_span_suggester.py"
    outputs:
      - "configs/${vars.config}.cfg"

  - name: train
    help: "Train the pipeline"
    script:
      - "python -m spacy train configs/${vars.config}.cfg -o models --gpu-id ${vars.gpu} \
        --code scripts/custom_span_suggester.py"
    deps:
      - "corpus/train.spacy"
      - "corpus/dev.spacy"
      - "configs/${vars.config}.cfg"
      - "scripts/custom_span_suggester.py"
    outputs:
      - "models/model-best"

  - name: evaluate
    help: "Evaluate results"
    script:
      - "python -m spacy evaluate models/model-best corpus/test.spacy -o metrics/model_best_metrics.json --gpu-id 0 --code scripts/custom_span_suggester.py"
    deps:
      - "assets/labels_and_predictions.jsonl"
      - "models/model-best"
      - "corpus/test.spacy"
      - "scripts/custom_span_suggester.py"
    outputs:
      - "models/model-best"
      - "metrics/model_best_metrics.json"

  - name: crossvalidation
    help: "Crossval"
    script:
      - "python -m spacy train configs/config.cfg -o models-cval/cval_0 --gpu-id 0 --code scripts/custom_span_suggester.py --paths.train corpus-cval/cval_0_train.spacy --paths.dev corpus-cval/cval_0_dev.spacy"
      - "python -m spacy train configs/config.cfg -o models-cval/cval_1 --gpu-id 0 --code scripts/custom_span_suggester.py --paths.train corpus-cval/cval_1_train.spacy --paths.dev corpus-cval/cval_1_dev.spacy"
      - "python -m spacy train configs/config.cfg -o models-cval/cval_2 --gpu-id 0 --code scripts/custom_span_suggester.py --paths.train corpus-cval/cval_2_train.spacy --paths.dev corpus-cval/cval_2_dev.spacy"
      - "python -m spacy train configs/config.cfg -o models-cval/cval_3 --gpu-id 0 --code scripts/custom_span_suggester.py --paths.train corpus-cval/cval_3_train.spacy --paths.dev corpus-cval/cval_3_dev.spacy"
      - "python -m spacy train configs/config.cfg -o models-cval/cval_4 --gpu-id 0 --code scripts/custom_span_suggester.py --paths.train corpus-cval/cval_4_train.spacy --paths.dev corpus-cval/cval_4_dev.spacy"
      - "python -m spacy train configs/config.cfg -o models-cval/cval_5 --gpu-id 0 --code scripts/custom_span_suggester.py --paths.train corpus-cval/cval_5_train.spacy --paths.dev corpus-cval/cval_5_dev.spacy"
    deps:
      - "corpus-cval/cval_0_train.spacy"
      - "corpus-cval/cval_0_dev.spacy"
      - "corpus-cval/cval_1_train.spacy"
      - "corpus-cval/cval_1_dev.spacy"
      - "corpus-cval/cval_2_train.spacy"
      - "corpus-cval/cval_2_dev.spacy"
      - "corpus-cval/cval_3_train.spacy"
      - "corpus-cval/cval_3_dev.spacy"
      - "corpus-cval/cval_4_train.spacy"
      - "corpus-cval/cval_4_dev.spacy"
      - "corpus-cval/cval_5_train.spacy"
      - "corpus-cval/cval_5_dev.spacy"
    outputs:
      - "models-cval/cval_0/model-best"
      - "models-cval/cval_1/model-best"
      - "models-cval/cval_2/model-best"
      - "models-cval/cval_3/model-best"
      - "models-cval/cval_4/model-best"
      - "models-cval/cval_5/model-best"

  - name: package
    help: "Generate an installable Python package from an existing pipeline data directory. All data files are copied over."
    script:
      - "python -m spacy package models/model-best packages --code scripts/custom_span_suggester.py --name entity_categorization"